# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a3bb492e0be18fcf92dbaa9b5c6cf610b3a3f0596225288224d97d50ac31aabb1e60e380efecba2b2db057ae184fdb6d9189fd41e72864aa05d6c1f9d6f35e8

test:
  secret_key_base: 7681adddcd7e97a718fa3f5360a18a31153547f74f47e336d9ae79a057ef26d1a97fcfffad7425c48211f53c0c366870fd15a9efcfbb5e1a8808d7b8ff0be515

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
